#!/bin/sh
	
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NORMAL='\033[0m'

# TODO: fix nvim submodule thing

mkdir -p $HOME/.local/share/gnupg $HOME/.cache/X11

DOT_HOME="$(pwd)/home"
for i in $(find "$DOT_HOME" -type f); do

	base="${i#$DOT_HOME/}"
	link="$HOME/$base"

	mkdir -p "$(dirname "$link")"
	
	if [ -e "$link" ] && [ ! -L "$link" ]; then
		echo "${RED}Warning: ${NORMAL}$link ${RED}already exists.${NORMAL}"
		echo -n "Do you want to overwrite it? ${NORMAL}[${GREEN}y${NORMAL}/${RED}N${NORMAL}]: "
		read answer

		if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
			rm -rf "$link"
		else
			echo "${YELLOW}Skipping ${NORMAL}$link${YELLOW} ...${NORMAL}\n"
			continue
		fi
	fi
	
	ln -sf "$i" "$link"
	echo "${GREEN}Linked ${NORMAL}$link ${GREEN}-> ${NORMAL}$i"
done

echo "All files from $DOT_HOME have been symlinked to $HOME."
