#!/bin/sh

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
while read file
do
	fullpath="$(pwd)/$file"
	case "$1" in
	"w")
		feh --no-fehbg --bg-max "$file" &&
		printf "%s\n%s\n" "#!/bin/sh" "feh --no-fehbg --bg-max \"$file\"" > $XDG_CONFIG_HOME/X11/wallpaper &&
		notify-send -u normal -i "$file" "was set as the wallpaper (centered)." ;;
	"z")
		feh --no-fehbg --bg-fill "$file" &&
		printf "%s\n%s\n" "#!/bin/sh" "feh --no-fehbg --bg-fill \"$file\"" > $XDG_CONFIG_HOME/X11/wallpaper &&
		notify-send -u normal -i "$file" "was set as the wallpaper (zoomed)." ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send -u normal -i "$file" "copied to the clipboard." ;;
	"r")
		magick convert -rotate 90 "$file" "$file" ;;
	"l")
		magick convert -rotate -90 "$file" "$file" ;;
	"f")
		magick convert -flop "$file" "$file" ;;
	"d")
		rm "$file" ;;
	esac
done
